BASE_URL = "https://www.alphavantage.co/query"
SYMBOL_SEARCH = "SYMBOL_SEARCH"
TIME_SERIES_INTRADAY = "TIME_SERIES_INTRADAY"
TIME_SERIES_DAILY = "TIME_SERIES_DAILY"
TIME_SERIES_WEEKLY = "TIME_SERIES_WEEKLY"
TIME_SERIES_MONTHLY = "TIME_SERIES_MONTHLY"

TIME_SERIES_DATA_MAPPING = {
    "1min": TIME_SERIES_INTRADAY,
}