BASE_URL = "https://www.alphavantage.co/query"
SYMBOL_SEARCH = "SYMBOL_SEARCH"
TIME_SERIES_INTRADAY = "TIME_SERIES_INTRADAY"
TIME_SERIES_DAILY = "TIME_SERIES_DAILY"
TIME_SERIES_WEEKLY = "TIME_SERIES_WEEKLY"
TIME_SERIES_MONTHLY = "TIME_SERIES_MONTHLY"
GLOBAL_QUOTE = "GLOBAL_QUOTE"

SUPPORTED_INDICATORS = [
    "SMA", "EMA", "WMA", "DEMA", "TEMA", "TRIMA", "KAMA",
    "MAMA", "VWAP", "T3", "MACD", "MACDEXT",
    "STOCH", "STOCHF", "RSI", "STOCHRSI", "WILLR",
    "ADX", "ADXR", "APO", "PPO", "MOM", "BOP", "CCI", "CMO",
    "ROC", "ROCR", "AROON", "AROONOSC", "MFI", "TRIX", "ULTOSC", "DX",
    "MINUS_DI", "PLUS_DI", "MINUS_DM", "PLUS_DM", "BBANDS", "MIDPOINT",
    "MIDPRICE", "SAR", "TRANGE", "ATR", "NATR", "AD", "ADOSC",
    "OBV", "HT_TRENDLINE", "HT_SINE", "HT_TRENDMODE", "HT_DCPERIOD",
    "HT_DCPHASE", "HT_PHASOR"
]
