version: "3"

services:
  alphavantage_app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    restart: on-failure
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - FLASK_APP=/alphavantage_app/main.py
    ports:
      - "5000:5000"
    command: "flask run --host=0.0.0.0"